//
//  Token.swift
//  FOO.BAR.BAS

enum Token: String {
    case _cr = "\n"
    
    case _if = "IF"
    case _then = "THEN"
    case _goto = "GOTO"
    case _let = "LET"
    case _print = "PRINT"
    case _end = "END"
    
    case _plus = "+"
    case _minus = "-"
    case _asterisk = "*"
    case _slash = "/"

    case _parenthesisLeft = "("
    case _parenthesisRight = ")"

    case _less = "<"
    case _greater = ">"
    case _equal = "="
    case _lessOrEqual = "<="
    case _greaterOrEqual = ">="
    case _notEqual = "<>"

    case _0 = "0"
    case _1 = "1"
    case _2 = "2"
    case _3 = "3"
    case _4 = "4"
    case _5 = "5"
    case _6 = "6"
    case _7 = "7"
    case _8 = "8"
    case _9 = "9"

    case _A = "A"
    case _B = "B"
    case _C = "C"
    case _D = "D"
    case _E = "E"
    case _F = "F"
    case _G = "G"
    case _H = "H"
    case _I = "I"
    case _J = "J"
    case _K = "K"
    case _L = "L"
    case _M = "M"
    case _N = "N"
    case _O = "O"
    case _P = "P"
    case _Q = "Q"
    case _R = "R"
    case _S = "S"
    case _T = "T"
    case _U = "U"
    case _V = "V"
    case _W = "W"
    case _X = "X"
    case _Y = "Y"
    case _Z = "Z"
}
